version: '3.3'

services:
   bbq_db:
     build:
       dockerfile: Dockerfile
       context: ./database
     volumes:
       - bbq_data:/var/lib/postgresql/data
     restart: always
     environment:
       POSTGRES_DB: bbq
       POSTGRES_USER: bbq
       POSTGRES_PASSWORD: bbq
   pidservice:
     depends_on:
       - bbq_db
     build:
       dockerfile: Dockerfile
       context: ./PidService
     volumes:
       - bbq_config:/config
     ports:
       - "12355:12355"
     restart: always
     environment:
       PIGPIO_ADDR: host.docker.internal
       PIGPIO_PORT: 8888
       DB_CONNECTION_STRING: postgresql+pg8000://bbq:bbq@bbq_db/bbq
volumes:
    bbq_data: {}
    bbq_config: {}
    
