version: '3.3'

services:
   bbq_db:
     build:
       dockerfile: Dockerfile
       context: ./database
     volumes:
       - bbq_data:/var/lib/postgresql/data
     restart: always
     environment:
       POSTGRES_DB: bbq
       POSTGRES_USER: bbq
       POSTGRES_PASSWORD: bbq
     ports:
       - "5432:5432"
   webserver:
     build:
       dockerfile: Dockerfile
       context: ./webserver
     ports:
       - "8080:8080"
     restart: always
     environment:
       DB_HOST: bbq_db
       DB_USER: bbq
       DB_PASSWORD: bbq
       DB_DBNAME: bbq
       DB_PORT: 5432
       PIDSERVICE_HOST: pidservice
       TZ: America/Chicago
   pidservice:
     depends_on:
       - bbq_db
     build:
       dockerfile: Dockerfile
       context: ./PidService
     volumes:
       - bbq_config:/config
     ports:
       - "12355:12355"
     #stdin_open: true
     #tty: true
     entrypoint: python3 server_main.py
     restart: always
     environment:
       PIGPIO_ADDR: pibbq.savage.zone
       PIGPIO_PORT: 8888
       DB_CONNECTION_STRING: postgresql+pg8000://bbq:bbq@bbq_db/bbq
       TZ: America/Chicago
volumes:
    bbq_data: {}
    bbq_config: {}
    
