CREATE VIEW pid_view AS 
select pid_state.time AS time,
pid_state.local_time AS local_time,
pid_state.oven_temp AS oven_temp,
pid_state.avg_oven_temp AS avg_oven_temp,
pid_state.output AS output,
pid_state.p_term AS p_term,
pid_state.d_term AS d_term,
pid_state.i_term AS i_term,
pid_state.error_sum AS error_sum,
pid_config.set_point AS set_point,
pid_config.kb AS kb,
pid_config.kp AS kp,
pid_config.ki AS ki,
pid_config.kd AS kd,
pid_config.smooth_coeff AS smooth_coeff,
pid_config.max_output AS max_output from (pid_state join pid_config on(pid_state.pid_config = pid_config.id));
